import { UserRole, Permission } from "../types";

export const ROLE_PERMISSIONS: Record<UserRole, Permission[]> = {
  [UserRole.SUPER_ADMIN]: Object.values(Permission),

  [UserRole.ADMIN]: [
    Permission.USERS_VIEW,
    Permission.USERS_CREATE,
    Permission.USERS_UPDATE,
    Permission.STUDENTS_VIEW,
    Permission.STUDENTS_CREATE,
    Permission.STUDENTS_UPDATE,
    Permission.STUDENTS_DELETE,
    Permission.STAFF_VIEW,
    Permission.STAFF_CREATE,
    Permission.STAFF_UPDATE,
    Permission.CLASSES_VIEW,
    Permission.CLASSES_MANAGE,
    Permission.SUBJECTS_VIEW,
    Permission.SUBJECTS_MANAGE,
    Permission.COURSES_VIEW,
    Permission.ATTENDANCE_VIEW,
    Permission.ATTENDANCE_MANAGE,
    Permission.ASSIGNMENTS_VIEW,
    Permission.GRADES_VIEW,
    Permission.FEES_VIEW,
    Permission.PAYMENTS_VIEW,
    Permission.EXPENSES_VIEW,
    Permission.INVOICES_VIEW,
    Permission.AUDIT_VIEW,
    Permission.MATERIALS_VIEW,
    Permission.ANNOUNCEMENTS_VIEW,
    Permission.ANNOUNCEMENTS_CREATE,
    Permission.MESSAGES_VIEW,
    Permission.SUPPORT_VIEW,
    Permission.SUPPORT_MANAGE,
    Permission.LIBRARY_VIEW,
    Permission.TRANSPORT_VIEW,
    Permission.HOSTEL_VIEW,
    Permission.ADMISSIONS_VIEW,
    Permission.ADMISSIONS_MANAGE,
    Permission.REPORTS_VIEW,
    Permission.REPORTS_EXPORT,
    Permission.SETTINGS_VIEW,
    Permission.SETTINGS_MANAGE,
    Permission.ONLINE_CLASSES_VIEW,
    Permission.EVENTS_VIEW,
    Permission.EVENTS_MANAGE,
    Permission.CALENDAR_VIEW,
    Permission.HR_VIEW,
    Permission.INVENTORY_VIEW,
  ],

  [UserRole.ACCOUNTANT]: [
    Permission.FEES_VIEW,
    Permission.FEES_MANAGE,
    Permission.PAYMENTS_VIEW,
    Permission.PAYMENTS_PROCESS,
    Permission.EXPENSES_VIEW,
    Permission.EXPENSES_MANAGE,
    Permission.INVOICES_VIEW,
    Permission.INVOICES_MANAGE,
    Permission.PAYROLL_VIEW,
    Permission.PAYROLL_MANAGE,
    Permission.AUDIT_VIEW,
    Permission.AUDIT_EXPORT,
    Permission.REPORTS_VIEW,
    Permission.REPORTS_EXPORT,
    Permission.STUDENTS_VIEW,
    Permission.ANNOUNCEMENTS_VIEW,
    Permission.MESSAGES_VIEW,
    Permission.SUPPORT_VIEW,
    Permission.CALENDAR_VIEW,
  ],

  [UserRole.TEACHER]: [
    Permission.STUDENTS_VIEW,
    Permission.CLASSES_VIEW,
    Permission.SUBJECTS_VIEW,
    Permission.COURSES_VIEW,
    Permission.COURSES_CREATE,
    Permission.COURSES_UPDATE,
    Permission.ATTENDANCE_VIEW,
    Permission.ATTENDANCE_MARK,
    Permission.ASSIGNMENTS_VIEW,
    Permission.ASSIGNMENTS_CREATE,
    Permission.ASSIGNMENTS_GRADE,
    Permission.GRADES_VIEW,
    Permission.GRADES_MANAGE,
    Permission.MATERIALS_VIEW,
    Permission.MATERIALS_UPLOAD,
    Permission.MATERIALS_MANAGE,
    Permission.ANNOUNCEMENTS_VIEW,
    Permission.MESSAGES_VIEW,
    Permission.MESSAGES_SEND,
    Permission.ONLINE_CLASSES_VIEW,
    Permission.ONLINE_CLASSES_HOST,
    Permission.EVENTS_VIEW,
    Permission.CALENDAR_VIEW,
    Permission.SUPPORT_VIEW,
  ],

  [UserRole.NON_TEACHING_STAFF]: [
    Permission.ATTENDANCE_VIEW,
    Permission.ATTENDANCE_MARK,
    Permission.TRANSPORT_VIEW,
    Permission.TRANSPORT_MANAGE,
    Permission.HOSTEL_VIEW,
    Permission.HOSTEL_MANAGE,
    Permission.INVENTORY_VIEW,
    Permission.INVENTORY_MANAGE,
    Permission.ANNOUNCEMENTS_VIEW,
    Permission.MESSAGES_VIEW,
    Permission.SUPPORT_VIEW,
    Permission.CALENDAR_VIEW,
    Permission.LEAVE_VIEW,
  ],

  [UserRole.LIBRARIAN]: [
    Permission.LIBRARY_VIEW,
    Permission.LIBRARY_MANAGE,
    Permission.STUDENTS_VIEW,
    Permission.ANNOUNCEMENTS_VIEW,
    Permission.MESSAGES_VIEW,
    Permission.SUPPORT_VIEW,
    Permission.CALENDAR_VIEW,
  ],

  [UserRole.HR]: [
    Permission.HR_VIEW,
    Permission.HR_MANAGE,
    Permission.STAFF_VIEW,
    Permission.STAFF_CREATE,
    Permission.STAFF_UPDATE,
    Permission.LEAVE_VIEW,
    Permission.LEAVE_MANAGE,
    Permission.PAYROLL_VIEW,
    Permission.ANNOUNCEMENTS_VIEW,
    Permission.MESSAGES_VIEW,
    Permission.REPORTS_VIEW,
    Permission.CALENDAR_VIEW,
    Permission.SUPPORT_VIEW,
  ],

  [UserRole.RECEPTIONIST]: [
    Permission.STUDENTS_VIEW,
    Permission.ADMISSIONS_VIEW,
    Permission.ADMISSIONS_MANAGE,
    Permission.ANNOUNCEMENTS_VIEW,
    Permission.MESSAGES_VIEW,
    Permission.MESSAGES_SEND,
    Permission.EVENTS_VIEW,
    Permission.CALENDAR_VIEW,
    Permission.SUPPORT_VIEW,
    Permission.SUPPORT_MANAGE,
  ],

  [UserRole.STUDENT]: [
    Permission.COURSES_VIEW,
    Permission.ASSIGNMENTS_VIEW,
    Permission.GRADES_VIEW,
    Permission.ATTENDANCE_VIEW,
    Permission.MATERIALS_VIEW,
    Permission.FEES_VIEW,
    Permission.PAYMENTS_VIEW,
    Permission.ANNOUNCEMENTS_VIEW,
    Permission.MESSAGES_VIEW,
    Permission.MESSAGES_SEND,
    Permission.ONLINE_CLASSES_VIEW,
    Permission.EVENTS_VIEW,
    Permission.CALENDAR_VIEW,
    Permission.LIBRARY_VIEW,
    Permission.SUPPORT_VIEW,
  ],

  [UserRole.PARENT]: [
    Permission.STUDENTS_VIEW,
    Permission.COURSES_VIEW,
    Permission.ASSIGNMENTS_VIEW,
    Permission.GRADES_VIEW,
    Permission.ATTENDANCE_VIEW,
    Permission.FEES_VIEW,
    Permission.PAYMENTS_VIEW,
    Permission.PAYMENTS_PROCESS,
    Permission.ANNOUNCEMENTS_VIEW,
    Permission.MESSAGES_VIEW,
    Permission.MESSAGES_SEND,
    Permission.EVENTS_VIEW,
    Permission.CALENDAR_VIEW,
    Permission.SUPPORT_VIEW,
  ],
};

export function hasPermission(role: UserRole, permission: Permission): boolean {
  return ROLE_PERMISSIONS[role]?.includes(permission) ?? false;
}

export function hasAnyPermission(role: UserRole, permissions: Permission[]): boolean {
  return permissions.some((p) => hasPermission(role, p));
}

export function hasAllPermissions(role: UserRole, permissions: Permission[]): boolean {
  return permissions.every((p) => hasPermission(role, p));
}

export function getRoleDashboardPath(role: UserRole): string {
  const paths: Record<UserRole, string> = {
    [UserRole.SUPER_ADMIN]: "/super-admin",
    [UserRole.ADMIN]: "/admin",
    [UserRole.ACCOUNTANT]: "/accountant",
    [UserRole.TEACHER]: "/teacher",
    [UserRole.NON_TEACHING_STAFF]: "/staff",
    [UserRole.LIBRARIAN]: "/librarian",
    [UserRole.HR]: "/hr",
    [UserRole.RECEPTIONIST]: "/receptionist",
    [UserRole.STUDENT]: "/student",
    [UserRole.PARENT]: "/parent",
  };
  return paths[role] ?? "/";
}

export * from "./routes";
